### ISSUE TITLE
senden von Messwerten an REST funktoniert nicht mehr 

### ISSUE THREAD

**Issue by Pixelherz23** [Pixelherz23/V.I.G-Mini#3]
Erhalte von Rest Schnittstelle `/greenhouse/measurements/new` folgende Nachricht:

```
502
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

```
JSON-Format:
```
Data
{
  "product_key": "GTD2-ERH6-E665",
  "led_status": 0,
  "temperature": "25.90",
  "humidity": 57,
  "soil_moisture": "0"
}
```

**Comment by Pixelherz23** [comment]
habs nochmal probiert mit ` "led_status": true,`, leider kein erfolg

**Comment by BeckiLukas** [comment]
Datenbank wurde angepasst: Dezimalwerte von temperature und und soil_moisture von (3,2) auf (5,2) geändert.
Funktioniert
